import express from 'express';import{createServer}from'node:http';import{WebSocketServer}from'ws';import crypto from'node:crypto';
const app=express(),http=createServer(app),wss=new WebSocketServer({server:http}),rooms=new Map(),PORT=Number(process.env.PORT||10000),C=['red','yellow','green','blue'],A=['skip','reverse','draw2'];
app.use(express.static('public'));app.get('/health',(_,r)=>r.json({ok:true,rooms:rooms.size}));app.get('*',(_,r)=>r.sendFile(process.cwd()+'/public/index.html'));
const id=()=>crypto.randomBytes(5).toString('hex'),send=(w,m)=>w?.readyState===1&&w.send(JSON.stringify(m)),shuf=a=>{for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function deck(){let d=[];for(const c of C){d.push({c,n:'0',u:id()});for(let n=1;n<10;n++)for(let i=0;i<2;i++)d.push({c,n:String(n),u:id()});for(const n of A)for(let i=0;i<2;i++)d.push({c,n,u:id()})}for(let i=0;i<4;i++){d.push({c:'wild',n:'wild',u:id()},{c:'wild',n:'wild4',u:id()})}return shuf(d)}
function refill(r){if(!r.d.length){let t=r.dis.pop();r.d=shuf(r.dis.splice(0));r.dis=[t]}}function draw(r,n){let x=[];while(n--){refill(r);if(r.d.length)x.push(r.d.pop())}return x}function next(r,steps=1){let i=r.turn;while(steps--)i=(i+r.dir+r.ps.length)%r.ps.length;return i}function label(c){return c.n==='draw2'?'+2':c.n==='wild4'?'Wild +4':c.n==='wild'?'Wild':c.n==='reverse'?'Reverse':c.n==='skip'?'Skip':c.n}
function pub(r){return{room:r.code,host:r.host,started:r.started,turn:r.ps[r.turn]?.id||null,direction:r.dir,color:r.color,discard:r.dis.at(-1),deckCount:r.d.length,players:r.ps.map(p=>({id:p.id,name:p.name,ready:p.ready,count:p.h.length,connected:!!p.ws})),winner:r.winner,message:r.message,pendingChallenge:r.challenge?{by:r.challenge.by,expires:r.challenge.expires}:null}}
function push(r,kind='state'){r.ps.forEach(p=>send(p.ws,{type:kind,state:{...pub(r),me:p.id,hand:p.h},log:r.log}))}function log(r,t){r.log.unshift({text:t,at:Date.now()});r.log=r.log.slice(0,60)}
function makeRoom(name,ws){let r={code:'',host:'',ps:[],started:false,dir:1,turn:0,color:'red',d:[],dis:[],winner:null,message:'Waiting for players',challenge:null,log:[]};do r.code=Math.random().toString(36).slice(2,8).toUpperCase();while(rooms.has(r.code));let p={id:id(),name:(name||'Player').slice(0,18),ws,h:[],ready:true,drew:false};r.host=p.id;r.ps=[p];rooms.set(r.code,r);return[r,p]}
function start(r){r.d=deck();r.ps.forEach(p=>{p.h=[];p.drew=false});for(let i=0;i<7;i++)r.ps.forEach(p=>p.h.push(r.d.pop()));let top;do{top=r.d.pop();if(top.c==='wild4')r.d.unshift(top),top=null}while(!top);r.dis=[top];r.color=top.c==='wild'?'red':top.c;r.dir=1;r.turn=0;r.challenge=null;r.winner=null;r.started=true;r.message='Game started';if(top.n==='reverse')r.dir=-1;if(top.n==='skip')r.turn=next(r);if(top.n==='draw2'){r.ps[0].h.push(...draw(r,2));r.turn=next(r)}log(r,'🎴 New round started');push(r)}
function legal(r,p,c){return c&&(c.c==='wild'||c.c===r.color||c.n===r.dis.at(-1).n)&&(c.n!=='wild4'||!p.h.some(x=>x.c===r.color||x.c==='wild'))}
function play(r,p,i,color){if(!r.started||r.challenge)return;let pi=r.ps.indexOf(p);if(pi!==r.turn)return send(p.ws,{type:'error',message:'It is not your turn.'});let c=p.h[i];if(!legal(r,p,c))return send(p.ws,{type:'error',message:'That card cannot be played.'});if(c.c==='wild'&&!C.includes(color))return send(p.ws,{type:'error',message:'Choose a color.'});p.h.splice(i,1);r.dis.push(c);r.color=c.c==='wild'?color:c.c;log(r,`${p.name} played ${label(c)}`);r.message=`${p.name} played ${label(c)}`;if(!p.h.length){r.started=false;r.winner=p.id;let pts=r.ps.reduce((s,x)=>s+(x.id===p.id?0:x.h.reduce((q,z)=>q+(z.c==='wild'?50:A.includes(z.n)?20:Number(z.n)||0),0)),0);r.message=`${p.name} wins · ${pts} points`;log(r,`🏆 ${p.name} wins the round`);return push(r)}if(p.h.length===1){p.unoUntil=Date.now()+3000;p.unoCalled=false;log(r,`🔴 ${p.name} is on UNO`)}let skip=c.n==='skip'||(c.n==='reverse'&&r.ps.length===2);if(c.n==='reverse')r.dir*=-1;if(c.n==='draw2'){r.turn=next(r);let v=r.ps[r.turn];v.h.push(...draw(r,2));log(r,`${v.name} draws 2`);r.turn=next(r)}else r.turn=next(r,skip?2:1);if(c.n==='wild4')r.challenge={by:p.id,expires:Date.now()+5000,hadColor:p.h.some(x=>x.c===r.dis.at(-1).c||x.c==='wild')};push(r)}
function act(r,p,a){let i=r.ps.indexOf(p);if(a==='ready'){p.ready=!p.ready;return push(r,'lobby')}if(a==='start'){if(p.id!==r.host)return;if(r.ps.length<2)return send(p.ws,{type:'error',message:'Need at least 2 players.'});if(!r.ps.every(x=>x.ready))return send(p.ws,{type:'error',message:'Everyone must be ready.'});return start(r)}if(a==='newround'){if(p.id===r.host&&r.ps.length>1)return start(r);return}if(a.a==='play')return play(r,p,a.index,a.color);if(a.a==='draw4'){if(i!==r.turn||!r.challenge)return;let v=r.ps[r.turn];v.h.push(...draw(r,4));r.challenge=null;r.message=`${v.name} takes +4`;log(r,`${v.name} draws 4 and loses the turn`);r.turn=next(r);return push(r)}if(a.a==='draw'){if(i!==r.turn||!r.started)return;if(r.challenge)return send(p.ws,{type:'error',message:'Choose Take +4 or Challenge.'});let x=draw(r,1);p.h.push(...x);p.drew=true;log(r,`${p.name} drew a card`);return push(r)}if(a.a==='pass'){if(i!==r.turn||!p.drew)return;p.drew=false;r.turn=next(r);return push(r)}if(a.a==='uno'){if(p.unoUntil&&Date.now()<=p.unoUntil&&p.h.length===1){p.unoCalled=true;log(r,`📣 ${p.name} called UNO`);push(r)}return}if(a.a==='catch'){let target=r.ps.find(x=>x.unoUntil&&x.id!==p.id);if(target&&Date.now()<=target.unoUntil&&target.h.length===1&&!target.unoCalled){target.h.push(...draw(r,2));target.unoUntil=null;log(r,`⚠️ ${p.name} caught ${target.name} without UNO`);push(r)}return}if(a.a==='challenge'){let q=r.challenge;if(!q||Date.now()>q.expires||q.by===p.id||p.id!==r.ps[r.turn]?.id)return;r.challenge=null;let offender=r.ps.find(x=>x.id===q.by);if(q.hadColor){offender.h.push(...draw(r,4));r.message=`Challenge succeeded · ${offender.name} draws 4`;log(r,'⚖️ Wild +4 challenge succeeded')}else{p.h.push(...draw(r,6));r.message=`Challenge failed · ${p.name} draws 6`;log(r,'⚖️ Wild +4 challenge failed')}r.turn=next(r);push(r)} }
function clean(r,p){p.ws=null;if(!r.started){r.ps=r.ps.filter(x=>x!==p);if(p.id===r.host)r.host=r.ps[0]?.id||'';if(!r.ps.length)rooms.delete(r.code);else push(r,'lobby')}else{log(r,`⚠️ ${p.name} disconnected`);push(r)}}
wss.on('connection',ws=>{let r=null,p=null;ws.on('message',b=>{let m;try{m=JSON.parse(b)}catch{return}if(m.type==='create'){[r,p]=makeRoom(String(m.name||'Player'),ws);send(ws,{type:'joined',state:{...pub(r),me:p.id,hand:p.h},log:r.log});push(r,'lobby');return}if(m.type==='join'){r=rooms.get(String(m.code||'').toUpperCase());if(!r||r.started||r.ps.length>=8)return send(ws,{type:'error',message:'Room not found, full, or already started.'});p={id:id(),name:String(m.name||'Player').slice(0,18),ws,h:[],ready:false,drew:false};r.ps.push(p);send(ws,{type:'joined',state:{...pub(r),me:p.id,hand:p.h},log:r.log});return push(r,'lobby')}if(r&&p&&m.type==='action')act(r,p,m.action)});ws.on('close',()=>r&&p&&clean(r,p))});
setInterval(()=>{for(const r of rooms.values()){for(const p of r.ps)if(p.unoUntil&&Date.now()>p.unoUntil&&!p.unoCalled){if(p.h.length===1){p.h.push(...draw(r,2));log(r,`⚠️ ${p.name} missed UNO and draws 2`)}p.unoUntil=null;push(r)}}for(const r of rooms.values())if(r.challenge&&Date.now()>r.challenge.expires){let v=r.ps[r.turn];r.challenge=null;if(v&&r.started){v.h.push(...draw(r,4));r.message=`${v.name} takes +4`;log(r,`${v.name} takes +4 and loses the turn`);r.turn=next(r);push(r)}}},500);
process.on('SIGTERM',()=>{wss.clients.forEach(w=>w.close(1001));http.close(()=>process.exit(0))});http.listen(PORT,'0.0.0.0',()=>console.log(`UNO listening on ${PORT}`));
